### ISSUE TITLE
Please Create a Contact Form

### ISSUE THREAD

**Issue by AnsarIbrahim** [peteronyam/Mobile-First-portfolio#3]
Hii Please I Suggest you need to create a contact form that looks like figma template

**Comment by helina42** [comment]
Please consider removing comments before submitting for a clean code.

**Comment by peteronyam** [comment]
Thank you so much, i am working on that already.

**Comment by Phone-Khaing-Hein** [comment]
You should remove the class attribute which is not used in some ul tags in index.html for better clean code.
