### ISSUE TITLE
Button need alignment

### ISSUE THREAD

**Issue by faisalakb** [peteronyam/Mobile-First-portfolio#6]
You need set the position of the button using flex properties

**Comment by tGemechis7** [comment]
@peteronyam 
you did great job
-there is some issue on stylesheet alignment

**Comment by arnoldnekemiah** [comment]
Please include social media icons in the footer.

**Comment by peteronyam** [comment]
Thank you so much for the comments, please check again as I have corrected the errors as highlighted
